[package]
name = "lib_trdp"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2.168"
clap = { version = "4.5.28", features = ["derive"] }

[env]
LD_LIBRARY_PATH = "../../trdp/bld/output/linux-rel/"

[build-dependencies]
bindgen = "0.71.1"
